### ISSUE TITLE
Páginas dinâmicas do Jinja2

### ISSUE THREAD

**Issue by joaodath** [joaodath/projeto_alexandria#4]
Criar as páginas dinâmicas do site com base no base.html

Início
Acervo
Cadastrar
Quem Somos
Página do Livro
Editar
Login
Cadastrar

**Comment by joaodath** [comment]
Páginas criadas! Farei um meet com @thaynar96 amanhã para explicar essa parte do projeto.

**Comment by Bianca-22** [comment]
João, eu fiquei sem internet o final de semana todo e só voltou agr, nem
assisti a aula.
Posso participar dessa reunião q vc vai fazer com a Thaynar, para eu ver
como q ta indo o projeto, sla? Vc pode me dizer o horário da reunião?

Em ter, 3 de ago de 2021 00:33, João Rodrigues ***@***.***>
escreveu:

**Comment by joaodath** [comment]
Oi, @Bianca-22 ! Vamos discutir no Codelab de hoje! :)
