### ISSUE TITLE
Merge Main e Deploy no Heroku

### ISSUE THREAD

**Issue by joaodath** [joaodath/projeto_alexandria#6]
Juntar todas as alterações da branches e deploy no Heroku.

**Comment by fharaujo** [comment]
Fo "eliminado" o flask_script e a interface de linha de comando manager.run() em app.py, porque NÃO precisamos utilizar em produção, uma vez que, o banco já foi criado e está funcionando remoto. 
OBS: Lembrando que em desenvolvimento é "necessário" utilizar a personalização dos comandos nas migrations do banco de dados. Porém, li agora pouco que podemos substituir o manager(tá meio largado), pelo CLI padrão que vem no flask chamado Click. Em desenvolvimento,  uma CLI ajudando nas migrations do banco e personalizando os comandos. Quando tiver que subir pra produção, descartamos a CLI e subimos com app.run()

**Comment by joaodath** [comment]
https://projetoalexandria-dev.herokuapp.com/
