### ISSUE TITLE
Seleção dos Livros

### ISSUE THREAD

**Issue by joaodath** [joaodath/projeto_alexandria#9]
Deixe aqui nos comentários 5 livros de gêneros diferentes. 
Modelo:

Nome do Livro
Nome do Autor
Ano de Lançamento
Avaliação do Livro (Buscar no Skoob.com.br)
Capa do Livro (link da imagem em alta resolução na internet)
Sinopse do Livro
Editora
Gênero
ISBN-13 (ou ISBN-10 se não houver o 13, encontra também no Skoob.com.br)
Quantidade de Páginas (Skoob.com.br)
Link de Compra na Amazon ou Link de Download no Domínio Público (http://www.dominiopublico.gov.br/pesquisa/PesquisaObraForm.jsp)

---

Próximo livro

**Comment by Bianca-22** [comment]
Nome do Livro: Anjo Negro

Nome do Autor: Lyan K. Levian

Ano de Lançamento: 17 de agosto de 2016

Avaliação do Livro: 4.2

Capa do Livro: https://www.google.com/search?q=anjo+negro+livro+lyan+k.+levian&tbm=isch&chips=q:anjo+negro+livro+lyan+k+levian,online_chips:kenan+russel:jSRbYWHArb8%3D&rlz=1C1SQJL_pt-BRBR945BR945&hl=pt-BR&sa=X&ved=2ahUKEwi7sNfa4YTyAhULHN8KHXgBAvwQ4lYoAnoECAEQFg&biw=1349&bih=657#imgrc=UDSgwKZBr-n4XM

Sinopse do Livro: Kenan Russel é novato na escola em plena metade do 3º colegial - um verdadeiro saco, na opinião dele. Mas sua personalidade desaforada e petulância fazem com que não se sinta intimidado pelos olhares que recebe por causa de sua aparência.
Já Lucio Corrêa, aluno daquela escola desde o primeiro colegial, é o extremo oposto de Kenan: vive encolhido na esperança de que não o notem. O bullying que sofre diariamente ensinou-o qual é seu lugar no mundo.
Kenan vê aí uma boa oportunidade de passar o tempo: quanto mais Lucio se encolhe na cadeira com suas provocações, mais quer incomodá-lo.
Porém, uma pequena atitude de Lucio faz com que Kenan comece a olhá-lo de forma diferente...

Editora: Independente

Gênero: +18 / Boys Love / Homoerótico / Superação / Preconceito / Ficção / Jovem Adulto / LGBT / Literatura Brasileira / Romance / Contos / Drama

ISBN-13: 978-8592239008

Quantidade de Páginas: 121

Link para baixar o livro de gratuitamente: https://lyanklevian.com/wp-content/uploads/2020/10/Anjo-Negro-Lyan-K-Levian-livro-yaoi-gratis.pdf

Link para comprar o livro: https://www.amazon.com.br/Anjo-Negro-Lyan-K-Levian/dp/8592239001

**Comment by menezesfelipee** [comment]
Nome do Livro: Eu Sou o Número Quatro

Nome do Autor: Pittacus Lore

Ano de Lançamento: 2011

Avaliação do Livro (Buscar no Skoob.com.br): 4.1

Capa do Livro (link da imagem em alta resolução na internet): https://images-na.ssl-images-amazon.com/images/I/61Gt+ylJbHL.jpg

Sinopse do Livro:

> "Nove de nós vieram para cá. Somos parecidos com vocês. Falamos como vocês. Vivemos entre vocês. Mas não somos vocês. Temos poderes que vocês apenas sonham ter. Somos mais fortes e mais rápidos que qualquer coisa que já viram. Somos os super-heróis que vocês idolatram nos filmes e nos quadrinhos mas somos reais.
> 
> Nosso plano era crescer, treinar, ser mais poderosos e nos tornar apenas um, e então combatê-los. Mas eles nos encontraram antes. E começaram a nos caçar. Agora, todos nós estamos fugindo.
> 
> O Número Um foi capturado na Malásia.
> 
> O Número Dois, na Inglaterra.
> 
> E o Número Três, no Quênia.
> 
> Eu sou o Número Quatro.
> 
> Eu sou o próximo."

Editora: Intrínseca

Gênero: Aventura / Infantojuvenil / Literatura Estrangeira

ISBN-13 (ou ISBN-10 se não houver o 13, encontra também no Skoob.com.br): 9788580570137

Quantidade de Páginas (Skoob.com.br): 352

Link de Compra na Amazon: https://www.amazon.com.br/Sou-N%C3%BAmero-Quatro-Pittacus-Lore/dp/8580570131

Link de Download (Prévia): https://www.intrinseca.com.br/upload/livros/1Cap_EuSouNumeroQuatro.pdf

**Comment by Bianca-22** [comment]
Nome do Livro: O Triste Fim de Policarpo Quaresma

Nome do Autor: Lima Barreto

Ano de Lançamento: 1984

Avaliação do Livro: 3.6

Capa do Livro: https://m.media-amazon.com/images/I/51ZM3FuRdRL.jpg

Sinopse do Livro: O Triste Fim de Policarpo Quaresma, de Lima Barreto, narra a trajetória de Policarpo Quaresma, um patriota ímpar, que causa estranheza nas pessoas pelos seus ideais e coragem. Policarpo era um homem respeitado pela vizinhança, mas ao mesmo tempo o estranhavam, por causa de seu amor pelos livros e pelo patriotismo exaltado.  Policarpo buscava coisas verdadeiramente brasileiras, desde comida, até a vestimenta. 

Editora: Moderna

Gênero: Ficção / 

ISBN-13: 9788537707661

Quantidade de Páginas: 256

Link para baixar o livro de gratuitamente: http://www.dominiopublico.gov.br/download/texto/bv000159.pdf

Link para comprar o livro: https://www.amazon.com.br/Triste-fim-Policarpo-Quaresma-B%C3%B4nus-ebook/dp/B07XGMS3L3

**Comment by Bianca-22** [comment]
Nome do Livro: 1984

Nome do Autor: George Orwell

Ano de Lançamento: 2009

Avaliação do Livro: 4.5

Capa do Livro: https://images-na.ssl-images-amazon.com/images/I/51feD87yuEL._SX321_BO1,204,203,200_.jpg

Sinopse do Livro:  Winston, herói de 1984, último romance de George Orwell, vive aprisionado na engrenagem totalitária de uma sociedade completamente dominada pelo Estado, onde tudo é feito coletivamente, mas cada qual vive sozinho. Ninguém escapa à vigilância do Grande Irmão, a mais famosa personificação literária de um poder cínico e cruel ao infinito, além de vazio de sentido histórico. De fato, a ideologia do Partido dominante em Oceânia não visa nada de coisa alguma para ninguém, no presente ou no futuro. O'Brien, hierarca do Partido, é quem explica a Winston que “só nos interessa o poder em si. Nem riqueza, nem luxo, nem vida longa, nem felicidade: só o poder pelo poder, poder puro”.

Editora: Companhia das Letras

Gênero: Distopia / Ficção / Literatura Estrangeira / Romance

ISBN-13:  9788535914849

Quantidade de Páginas: 416

Link para baixar o livro de gratuitamente: https://edisciplinas.usp.br/pluginfile.php/4118309/mod_resource/content/1/1984%20-%20George%20Orwell.pdf

Link para comprar o livro: https://www.amazon.com.br/1984-George-Orwell/dp/8535914846

**Comment by Bianca-22** [comment]
Nome do Livro: É Fácil Matar

Nome do Autor: Agatha Christie

Ano de Lançamento: 2015

Avaliação do Livro: 4.0

Capa do Livro: https://images-na.ssl-images-amazon.com/images/I/41iwducSGnL._SX322_BO1,204,203,200_.jpg

Sinopse do Livro: É por mera educação que o policial aposentado Luke Fitzwilliam dá atenção à simpática e tagarela srta. Pinkerton, que está sentada ao seu lado no trem para Londres. Ela lhe confidencia que está indo à Scotland Yard para denunciar uma série de assassinatos, e ele tem certeza de que ela perdeu o juízo. Mas quando a srta. Pinkerton morre de forma suspeita, Luke decide ir até o vilarejo onde ela residia a fim de investigar – e se depara com algo muito mais assustador do que poderia imaginar. É fácil matar, publicado pela primeira vez em 1939, combina romance e suspense numa trama que é considerada uma das mais surpreendentes já escritas pela Rainha do Crime.

Editora: L&PM Editores

Gênero: Crime / Ficção / Romance policial / Suspense e Mistério

ISBN-13: 9788525431974

Quantidade de Páginas: 272

Link de Compra na Amazon: https://www.amazon.com.br/%C3%89-f%C3%A1cil-matar-Agatha-Christie/dp/6555111364#:~:text=%C3%89%20f%C3%A1cil%20matar%20Capa%20dura%20%E2%80%93%2017%20maio%202021&text=O%20policial%20Luke%20Fitzwilliam%20retorna,em%20seu%20pequeno%20vilarejo%2C%20Wychwood.

Link de Download no Domínio Público: https://www.epedagogia.com.br/materialbibliotecaonine/2639E-Facil-Matar.pdf

**Comment by Bianca-22** [comment]
Nome do Livro: Assassinato No Expresso do Oriente

Nome do Autor: Agatha Christie

Ano de Lançamento: 2009

Avaliação do Livro: 4.3

Capa do Livro:  https://images-na.ssl-images-amazon.com/images/I/51dnONz-NjL._SX298_BO1,204,203,200_.jpg

Sinopse do Livro: Pouco depois da meia-noite, uma tempestade de neve para o Expresso do Oriente nos trilhos. O luxuoso trem está surpreendentemente cheio para essa época do ano. Mas, na manhã seguinte, há um passageiro a menos. Um americano é encontrado morto em sua cabina, com doze facadas, e a porta estava trancada por dentro. Pistas falsas são colocadas no caminho de Hercule Poirot para tentar mantê-lo fora de cena, mas, num dramático desenlace, ele apresenta não uma, mas duas soluções para o crime.

Editora: L&PM Editores

Gênero: Romance policial

ISBN-13: 978-8525430090

Quantidade de Páginas: 224

Link de Compra na Amazon: https://www.amazon.com.br/Assassinato-no-Expresso-Oriente-1155/dp/8525430099/ref=sr_1_2?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2928PD9LBDTBZ&dchild=1&keywords=assassinato+no+expresso+do+oriente&qid=1627606308&s=books&sprefix=assassinato%2Cstripbooks%2C279&sr=1-2

Link de Download no Domínio Público: https://kbook.com.br/wp-content/files_mf/assassinatonoexpressodoorienteagathachristie.pdf

**Comment by menezesfelipee** [comment]
Nome do Livro: A Volta Ao Mundo Em 80 Dias

Nome do Autor: Julio Verne

Ano de Lançamento: 1873

Avaliação do Livro (Buscar no Skoob.com.br): 4.1

Capa do Livro: https://images-na.ssl-images-amazon.com/images/I/91rI1L9mbBL.jpg

Sinopse do Livro:

> Phileas Fogg tinha uma vida regrada e solitaria, mas com muito dinheiro. Devido a uma aposta com seus amigos, resolve dar a volta ao mundo em 80 dias, acompanhado apenas de seu fiel empregado. Nessa viagem, vivera diversas aventuras e conhecera varios lugares do mundo. Sera que Fogg conseguira ganhar a aposta?

Editora: Martin Claret

Gênero: Aventura

ISBN-13: 9788572322881

Quantidade de Páginas: 240

Link de Compra na Amazon: https://www.amazon.com.br/dp/8572322884?tag=s0b61-20&linkCode=osi&th=1&psc=1#detailBullets_feature_div

Link de Dowload: http://www.dominiopublico.gov.br/download/texto/eb000003.pdf

**Comment by menezesfelipee** [comment]
Nome do Livro: Viagem ao Centro da Terra

Nome do Autor: Julio Verne

Ano de Lançamento: 1865

Avaliação do Livro (Buscar no Skoob.com.br): 4.0

Capa do Livro: https://revistacontinente.com.br/public/uploads/data/files/Edicao_168/viagem.jpg

Sinopse do Livro:

> Axel está prestes a viver a aventura de sua vida, ainda que a contragosto. Obrigado pelo tio a acompanhá-lo numa expedição ao centro do planeta, o jovem e perspicaz narrador diverte o leitor com seu bem-humorado relato da jornada, angustiado diante das excentricidades do genial professor Otto Lidenbrock e de seu impassível guia Hans. Fruto de meticulosa pesquisa, Viagem ao centro da Terra alia entretenimento a informação. Explorando culturas, cidades e mares, reconstrói a evolução do planeta e prova que nada é impossível quando se tem coragem. Pelo menos, o bastante para encarar uma inversão fascinante e, ao mesmo tempo, terrível bem debaixo de nossos pés: uma aparente semelhança revela o mais profundo estranhamento de nosso próprio mundo, colocando em xeque todo o conhecimento de uma sociedade. Mas é da destruição que surge o prazer da descoberta. A narrativa detalhada, poderosa e ritmada nos desafia a correr à internet para procurar cada lugar, checar cada informação. Até o momento em que o leitor perceberá estar como Verne queria cativado e irremediavelmente curioso, ávido por entender melhor seu mundo e a si próprio.

Editora: Ática

Gênero: Aventura

ISBN-13: 9788508145539

Quantidade de Páginas: 276

Link de Compra na Amazon: https://www.amazon.com.br/Viagem-Centro-Terra-Cole%C3%A7%C3%A3o-Leio/dp/8508145535

Link de Dowload: https://memoria.ebc.com.br/sites/_portalebc2014/files/atoms/files/-viagem_ao_centro_da_terra_-_julio_verne.pdf

**Comment by menezesfelipee** [comment]
Nome do Livro: Vinte mil Léguas Submarinas

Nome do Autor: Julio Verne

Ano de Lançamento: 1870

Avaliação do Livro (Buscar no Skoob.com.br): 3.8

Capa do Livro: https://images-na.ssl-images-amazon.com/images/I/9144tixbv5L.jpg

Sinopse do Livro:

> O ano de 1866 foi marcado por um acontecimento peculiar, um fenômeno inexplicado e inexplicável de que, sem dúvida, ninguém se esqueceu. Sem falar dos rumores que agitavam as populações dos portos e deixavam o público por demais inquieto no interior dos continentes, os que viviam no mar ficaram particularmente abalados.
> 
> Nesta aventura, Verne constrói um submarino ultra moderno para a época, o Náutilus. Nele, o capitão Nemo e sua tripulação cortam relações com a humanidade e partem para um aventura marítima, já que para a sobrevivência precisam apenas da eletricidade obtida na imensidão do mar.

Editora: Principis

Gênero: Aventura

ISBN-13: 9788594318763

Quantidade de Páginas: 368

Link de Compra na Amazon: https://www.amazon.com.br/Vinte-l%C3%A9guas-submarinas-J%C3%BAlio-Verne/dp/8594318766

Link de Dowload: https://www.itapema.sc.gov.br/wp-content/uploads/2020/03/Vinte-mil-leguas.pdf

**Comment by menezesfelipee** [comment]
Nome do Livro: Os Miseráveis

Nome do Autor: Victor Hugo

Ano de Lançamento: 1862

Avaliação do Livro (Buscar no Skoob.com.br): 4.5

Capa do Livro: https://images-na.ssl-images-amazon.com/images/I/91ew26UUzCL.jpg

Sinopse do Livro:

> Um clássico da literatura mundial, Esta obra é uma poderosa denúncia a todos os tipos de injustiça humana. Narra a emocionante história de Jean Valjean — o homem que, por ter roubado um pão, é condenado a dezenove anos de prisão. Os miseráveis é um livro inquietantemente religioso e político com uma das narrativas mais envolventes já criadas.

Editora: Martin Claret

Gênero: Drama

ISBN-13: 9788544000007

Quantidade de Páginas: 1511

Link de Compra na Amazon: https://www.amazon.com.br/Os-Miser%C3%A1veis-Victor-Hugo/dp/8544000002

Link de Dowload: https://www.companhiadasletras.com.br/trechos/55056.pdf

**Comment by joaodath** [comment]
### Todos os meus 5 livros:

--------------------------------------------------------

Nome do Livro: Torto Arado

Nome do Autor: Itamar Vieira Junior

Ano de Lançamento: 2019

Avaliação do Livro: 4.7

Capa do Livro: Salvo Localmente 

Sinopse do Livro:
Nas profundezas do sertão baiano, as irmãs Bibiana e Belonísia encontram uma velha e misteriosa faca na mala guardada sob a cama da avó. Ocorre então um acidente. E para sempre suas vidas estarão ligadas, a ponto de uma precisar ser a voz da outra. Numa trama conduzida com maestria e com uma prosa melodiosa, o romance conta uma história de vida e morte, de combate e redenção. Um texto épico e lírico, realista e mágico que revela, para além de sua trama, um poderoso elemento de insubordinação social.

Editora: Todavia

Ficção / Literatura Brasileira / Romance

ISBN-13: 9786580309313

Páginas: 264

Link de Compra: https://www.amazon.com.br/Torto-arado-Itamar-Vieira-Junior/dp/6580309318/ref=sr_1_3?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2YXTJZZZE4P8C&dchild=1&keywords=torto+arado&qid=1627876039&s=books&sprefix=torto+%2Caps%2C269&sr=1-3

----------------------------

Nome do Livro: Aristóteles e Dante descobrem os Segredos do Universo

Nome do Autor: Benjamin Alire Sáenz

Ano de Lançamento: 2014

Avaliação do Livro (Buscar no Skoob.com.br): 4.6

Capa do Livro (link da imagem em alta resolução na internet): https://m.media-amazon.com/images/I/51pbO2Ohi-L.jpg

Sinopse do Livro:
Dante sabe nadar. Ari não. Dante é articulado e confiante. Ari tem dificuldade com as palavras e duvida de si mesmo. Dante é apaixonado por poesia e arte. Ari se perde em pensamentos sobre seu irmão mais velho, que está na prisão.

Um garoto como Dante, com um jeito tão único de ver o mundo, deveria ser a última pessoa capaz de romper as barreiras que Ari construiu em volta de si. Mas quando os dois se conhecem, logo surge uma forte ligação. Eles compartilham livros, pensamentos, sonhos, risadas - e começam a redefinir seus próprios mundos. Assim, descobrem que o amor e a amizade talvez sejam a chave para desvendar os segredos do Universo.

Editora: Seguinte

Gênero: Ficção / Jovem adulto / LGBT / GLS / Literatura Estrangeira 

ISBN-13: 9788565765350

Páginas: 392

Link de Compra: https://www.amazon.com.br/Arist%C3%B3teles-Dante-descobrem-segredos-universo/dp/8565765350/ref=sr_1_1?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=Arist%C3%B3teles+e+Dante+Descobrem+os+Segredos+do+Universo&qid=1627876260&sr=8-1

-----------------------

Nome do Livro: Memórias Póstumas de Brás Cubas

Nome do Autor: Machado de Assis

Edição 01: 1881

Edição Martin Claret: 1999

Nota: 4.1

IMG: https://livrariascuritiba.vteximg.com.br/arquivos/ids/1541309-1000-1000/lv274394_1.jpg?v=636693382143830000

Sinopse: 
É após a morte que Brás Cubas decide narrar suas memórias. Nesta condição, nada pode suavizar seu ponto de vista irônico e mordaz sobre uma sociedade em que as instituições se baseiam na hipocrisia. O casamento, o adultério, os comportamentos individuais e sociais não escapam à sua visão aguda e implacável, nesta obra fundamental de Machado de Assis.

Editora Martin Claret

Literatura Brasileira / Ficção / Romance

ISBN-13: 9788572322942

Páginas: 224

Link de Download (Domínio Público): http://www.dominiopublico.gov.br/download/texto/bn000167.pdf

-----------------------------------------------

Nome do Livro: Os sete maridos de Evelyn Hugo

Nome do Autor: Taylor Jenkins Reid

Ano de Lançamento: 2019

Avaliação do Livro (Buscar no Skoob.com.br): 4.7

Capa do Livro (link da imagem em alta resolução na internet): https://images-na.ssl-images-amazon.com/images/I/91yEPgRcELL.jpg

Sinopse do Livro:
Lendária estrela de Hollywood, Evelyn Hugo sempre esteve sob os holofotes -- seja estrelando uma produção vencedora do Oscar, protagonizando algum escândalo ou aparecendo com um novo marido... pela sétima vez. Agora, prestes a completar oitenta anos e reclusa em seu apartamento no Upper East Side, a famigerada atriz decide contar a própria história -- ou sua "verdadeira história" --, mas com uma condição: que Monique Grant, jornalista iniciante e até então desconhecida, seja a entrevistadora. Ao embarcar nessa misteriosa empreitada, a jovem repórter começa a se dar conta de que nada é por acaso -- e que suas trajetórias podem estar profunda e irreversivelmente conectadas.

"Evelyn Hugo faz Elizabeth Taylor parecer sem graça. Você vai rir com ela, chorar, sofrer, e então voltar para a primeira página e fazer tudo de novo." -- Heather Cocks e Jessica Morgan, autoras de The Royal We

Editora: Paralela

Gênero: Ficção / LGBT / GLS / Literatura Estrangeira / Romance 

ISBN-13: 9788584391509

Páginas: 360

Link de Compra: https://www.amazon.com.br/Os-sete-maridos-Evelyn-Hugo/dp/8584391509/ref=sr_1_2?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=Arist%C3%B3teles+e+Dante+Descobrem+os+Segredos+do+Universo&qid=1627876312&sr=8-2

------------------------------------------------

Nome do Livro: O Teorema Katherine

Nome do Autor: John Green

Ano de Lançamento: 2013

Avaliação do Livro (Buscar no Skoob.com.br): 3.5

Capa do Livro (link da imagem em alta resolução na internet): https://m.media-amazon.com/images/I/41bEddLeVGL.jpg

Sinopse do Livro:
 Se o assunto é relacionamento, o tipo de garota de Colin Singleton tem nome: Katherine. E, em se tratando de Colin e Katherines, o desfecho é sempre o mesmo: ele leva o fora. Já aconteceu muito. Dezenove vezes, para ser exato.

Após o mais recente e traumático pé na bunda, o Colin que só namora Katherines resolve cair na estrada. Dirigindo o Rabecão de Satã, com seu caderninho de anotações no bolso e o melhor amigo no carona, o ex-garoto prodígio, viciado em anagramas e PhD em levar o fora, descobre sua verdadeira missão: elaborar e comprovar o Teorema Fundamental da Previsibilidade das Katherines, que tornará possível antever, através da linguagem universal da matemática, o desfecho de qualquer relacionamento antes mesmo que as duas pessoas se conheçam.

Uma descoberta que vai entrar para a história, vai vingar séculos de injusta vantagem entre Terminantes e Terminados e, enfim, elevará Colin Singleton diretamente ao distinto posto de gênio da humanidade. Também, é claro, vai ajudá-lo a reconquistar sua garota. Ou, pelo menos, é isso o que ele espera. 

Editora: Intrínseca 

Gênero: Romance / Jovem adulto / Literatura Estrangeira 

ISBN-13:  978-8580573152 

Páginas: 304

Link de Compra: https://www.amazon.com.br/Teorema-Katherine-Jonh-Green/dp/8580573157/ref=sr_1_1?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1HCP3FTXVOVAA&dchild=1&keywords=o+teorema+katherine&qid=1627876552&sprefix=teorema+%2Caps%2C258&sr=8-1

**Comment by thaynarbo** [comment]
Nome do Livro: O Grande Gatsby

Nome do Autor: F. Scott Fitzgerald

Ano de Lançamento: 2021

Avaliação do Livro: 4.1

Capa do Livro: https://cdn.awsli.com.br/1304/1304678/produto/106035431/afe4cbad83.jpg

Sinopse do Livro:
Jay Gatsby, o anfitrião milionário de monumentais festas em sua mansão, suscita muita desconfiança em seus convidados no que diz respeito à origem de sua fortuna, obtida após sua participação na Primeira Guerra Mundial. Gatsby é apaixonado há anos por Daisy, uma aristocrata casada com o astro esportivo Tom Buchanan, e prima de Nick Carraway, um corretor de títulos que vive em Long Island, em uma casa vizinha à do protagonista.
Ao ser enfim convidado para uma das festas da Gatsy, Nick se torna seu amigo e, por meio dessa relação, Gatsy busca se aproximar de Daisy na esperança de reatar o velho romance, agora que se tornou um homem rico e capaz de impressioná-la.
O triângulo amoroso entre Daisy, Gatsby e Tom começa a ganhar ares de tensão até que culmina em uma sucessão de tragédias, revelando a verdadeira face dos personagens e da sociedade aristocrata norte-americana da década de 1920, marcada pela busca pelo glamour e pelo materialismo desenfreado.
Escrito pelo célebre autor americano F. Scott Fitzgerald, O grande Gatsby é considerado uma das melhores obras literárias do século XX.

Editora: Excelsior

Ficção / Literatura Estrangeira / Romance / Drama

ISBN-13: 9786587435305

Páginas: 224

Link de Compra: https://www.amazon.com.br/grande-Gatsby-F-Scott-Fitzgerald-ebook/dp/B097NB7DSB/ref=sr_1_14?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=34V8IK82L7DSO&dchild=1&keywords=o+grande+gatsby&qid=1627940602&s=digital-text&sprefix=o+grande+gat%2Cdigital-text%2C284&sr=1-14

**Comment by thaynarbo** [comment]
Nome do Livro: O Lado Feio do Amor

Nome do Autor: Colleen Hoover

Ano de Lançamento: 2015

Avaliação do Livro (Buscar no Skoob.com.br): 4.2

Capa do Livro (link da imagem em alta resolução na internet): https://imagens.lelivros.love/2015/06/Baixar-Livro-O-Lado-Feio-Do-Amor-Colleen-Hoover-em-PDF-ePub-e-Mobi-370x559.jpg

Sinopse do Livro:
Quando Tate Collins se muda para o apartamento de seu irmão, Corbin, a fim de se dedicar ao mestrado em enfermagem, não imaginava conhecer o lado feio do amor. Um relacionamento onde companheirismo e cumplicidade não são prioridades. E o sexo parece ser o único objetivo. Mas Miles Archer, piloto de avião, vizinho e melhor amigo de Corbin, sabe ser persuasivo... apesar da armadura emocional que usa para esconder um passado de dor. O que Miles e Tate sentem não é amor à primeira vista, mas uma atração incontrolável. Em pouco tempo não conseguem mais resistir e se entregam ao desejo. O rapaz impõe duas regras: sem perguntas sobre o passado e sem esperanças para o futuro. Será um relacionamento casual. Eles têm a sintonia perfeita. Tate prometeu não se apaixonar. Mas vai descobrir que nenhuma regra é capaz de controlar o amor e o desejo.

Editora: Galera Record
Erótico / Ficção / Literatura Estrangeira / Romance / Jovem adulto

ISBN-13: 9788501105738

Páginas: 336

Link de Compra: https://www.amazon.com.br/lado-feio-do-amor-ebook/dp/B0141LGDZO/ref=sr_1_1?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=o+lado+feio+do+amor&qid=1627940825&s=digital-text&sr=1-1

**Comment by fharaujo** [comment]
Nome do Livro:  Consciência de Classe
Autor:  George Lukács   
ISBN: 9788533619258
Ano de lançamento: 1920
Avaliação: 3.7
Páginas: 100
capa: https://m.media-amazon.com/images/I/513+pqUBxEL._SY346_.jpg
sinopse: 
O legendário livro de Lukács exerceu sua primeira e profunda influência sobre a jovem inteligência como expressão teórica das transformações histórico-mundiais dos anos 20. Lukács deparava messiânica e efusivamente a dialética marxista: "Não é o predomínio de motivos econômicos na explicação da história que distingue de maneira determinante o marxismo da ciência burguesa, mas o ponto de vista da totalidade." Conferir à totalidade uma posição central em contraste com a prioridade do econômico correspondia à crítica radical de esquerda às posições da socialdemocracia. Seus próprios pontos de partida para uma leitura crítica da história e para uma discussão com o alcance das teses teóricas e políticas apresentadas neste volume foram formulados pelo próprio Lukács num posfácio de 1967, que se tornou parte das novas edições e de todas as traduções.
genero:  Filosofia

Link dominio publico: 
http://www.dominiopublico.gov.br/download/texto/ma000008.pdf
=========================================================================

Nome do Livro
O Anticristo

Nome do Autor
Friedrich Nietzsche

Ano de Lançamento
1888
Avaliação do Livro 
4.0
Capa do Livro (link da imagem em alta resolução na internet)
https://a-static.mlcdn.com.br/1500x1500/livro-o-anticristo/cliquebooks/112162-6/3f23bd764b071de4affb5ba08d8d314b.jpg

Sinopse do Livro
 Este ensaio é uma das mais afiadas análises de que o cristianismo já foi objeto. Dando continuidade ao exame sobre a moral praticado na maioria de seus livros, em "O anticristo" o autor firma sua posição sobre a doutrina religiosa. Ele mostra como o cristianismo – ao qual chama de maldição – é a vitória dos fracos, doentes e rancorosos sobre os fortes, orgulhosos e saudáveis, persuadindo e induzindo a massa por meio de ideias pré-fabricadas.
Editora
L&PM
Gênero
Filosofia
ISBN-13
9788525417916

Quantidade de Páginas
128
Link de Compra na Amazon ou Link de Download no Domínio Público
http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=2790

=========================================================================

Nome do Livro
O Banquete (o amor, o belo)
Nome do Autor
Platão
Ano de Lançamento
380 a.C. / 2012
Avaliação do Livro 
4.1
Capa do Livro
https://m.media-amazon.com/images/I/514A5h37gkL._SY346_.jpg

Sinopse do Livro
O Banquete, também conhecido como Simpósio é um diálogo platônico escrito por volta de 380 a.C.. Constitui-se basicamente de uma série de discursos sobre a natureza e as qualidades do amor (eros). O Banquete é, juntamente com o Fedro, um dos dois diálogos de Platão em que o tema principal é o amor.

Editora
Dominio Público
Gênero
Filosofia
ISBN-13
9788525417671
Quantidade de Páginas
71
Link de Compra na Amazon ou Link de Download no Domínio Público
http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=2279

=========================================================================

Nome do Livro
Crítica da Razão Pura
Nome do Autor
 Immanuel Kant
Ano de Lançamento
2007 
Avaliação do Livro 
4.2
Capa do Livro 
https://images-na.ssl-images-amazon.com/images/I/41Ht8zWiRqL._SX341_BO1,204,203,200_.jpg

Sinopse do Livro
A Filosofia transcendental é a ideia de uma ciência para a qual a crítica da razão pura fará o plano total, de um modo arquitetônico, ou seja, por princípios e com perfeição segura e garantia dos princípios da razão pura. A crítica não pode se denominar Filosofia transcendental, pois não contém uma análise pormenorizada dos nossos conhecimentos “a priori” para ser um sistema completo. Na verdade, nossa Crítica, com certeza, precisa colocar diante dos olhos também uma total enumeração dos conceitos primitivos que perfazem o mencionado conhecimento puro. 

Editora
ícone

Gênero
Filosofia

ISBN-13 
9788527409278
Quantidade de Páginas 
542 
Link de Compra na Amazon ou Link de Download no Domínio Público
http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=2246

=========================================================================

Nome do Livro
Apologia de Sócrates
Nome do Autor
Platão
Ano de Lançamento
2008
Avaliação do Livro 
4.2
Capa do Livro (link da imagem em alta resolução na internet)
Sinopse do Livro
O julgamento de Sócrates (469-399 a.C.) foi um dos fatos históricos mais importantes da Grécia Antiga e até hoje inspira escritores, artistas e filósofos. Em 399 a.C., Atenas estava se recompondo após a derrota para Esparta na Guerra do Peloponeso, tentando consolidar o ainda frágil regime democrático. O posicionamento crítico de Sócrates pareceu uma afronta aos costumes da cidade e ele foi incriminado, julgado e condenado à morte por envenenamento sob as acusações de não cultuar os deuses da cidade, tentar introduzir novas divindades e corromper a juventude com suas idéias. As acusações não intimidaram o pensador, que decidiu conduzir a própria defesa, dando origem aos textos aqui reunidos, Êutifron, Apologia de Sócrates e Críton. São obras que partem da discussão filosófica, mas assumem ramificações religiosas, políticas e éticas, mostrando por que Sócrates passou para a História como fundador da tradição filosófica ocidenta

Editora
 L&PM

Gênero
Filosofia

ISBN-13 
9788525417671

Quantidade de Páginas (Skoob.com.br)
144
Link de Compra na Amazon ou Link de Download no Domínio Público
http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=6693

**Comment by menezesfelipee** [comment]
Pronto.
